// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apotek_codes.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApotekCode = `-- name: CreateApotekCode :one
INSERT INTO apotek_codes (apotek_id, code, expires) 
VALUES ($1, $2, $3) RETURNING apotek_id, code, expires, created_at, updated_at
`

type CreateApotekCodeParams struct {
	ApotekID pgtype.UUID        `json:"apotek_id"`
	Code     string             `json:"code"`
	Expires  pgtype.Timestamptz `json:"expires"`
}

func (q *Queries) CreateApotekCode(ctx context.Context, arg CreateApotekCodeParams) (ApotekCode, error) {
	row := q.db.QueryRow(ctx, createApotekCode, arg.ApotekID, arg.Code, arg.Expires)
	var i ApotekCode
	err := row.Scan(
		&i.ApotekID,
		&i.Code,
		&i.Expires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApotekCode = `-- name: GetApotekCode :one
SELECT apotek_id, code, expires, created_at, updated_at FROM apotek_codes
WHERE apotek_id = $1
`

func (q *Queries) GetApotekCode(ctx context.Context, apotekID pgtype.UUID) (ApotekCode, error) {
	row := q.db.QueryRow(ctx, getApotekCode, apotekID)
	var i ApotekCode
	err := row.Scan(
		&i.ApotekID,
		&i.Code,
		&i.Expires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApotekCodeByCode = `-- name: GetApotekCodeByCode :one
SELECT apotek_id, code, expires, created_at, updated_at FROM apotek_codes
WHERE code = $1
`

func (q *Queries) GetApotekCodeByCode(ctx context.Context, code string) (ApotekCode, error) {
	row := q.db.QueryRow(ctx, getApotekCodeByCode, code)
	var i ApotekCode
	err := row.Scan(
		&i.ApotekID,
		&i.Code,
		&i.Expires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
