// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Owner struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Username  string             `json:"username"`
	Password  []byte             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Pharmacy struct {
	ID      int32       `json:"id"`
	OwnerID int32       `json:"owner_id"`
	Name    pgtype.Text `json:"name"`
}

type User struct {
	ID         int32              `json:"id"`
	Username   string             `json:"username"`
	Password   []byte             `json:"password"`
	PharmacyID int32              `json:"pharmacy_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
