// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: owners.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOwner = `-- name: CreateOwner :one
INSERT INTO owners (username, email, password_hash) 
VALUES ($1, $2, $3) RETURNING id, email, username, created_at, updated_at
`

type CreateOwnerParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash []byte `json:"password_hash"`
}

type CreateOwnerRow struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Username  string             `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOwner(ctx context.Context, arg CreateOwnerParams) (CreateOwnerRow, error) {
	row := q.db.QueryRow(ctx, createOwner, arg.Username, arg.Email, arg.PasswordHash)
	var i CreateOwnerRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnerByID = `-- name: GetOwnerByID :one
SELECT id, email, username, password_hash, created_at, updated_at FROM owners
WHERE id = $1
`

func (q *Queries) GetOwnerByID(ctx context.Context, id int32) (Owner, error) {
	row := q.db.QueryRow(ctx, getOwnerByID, id)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnerByUsername = `-- name: GetOwnerByUsername :one
SELECT id, username, password_hash FROM owners
WHERE username = $1
`

type GetOwnerByUsernameRow struct {
	ID           int32  `json:"id"`
	Username     string `json:"username"`
	PasswordHash []byte `json:"password_hash"`
}

func (q *Queries) GetOwnerByUsername(ctx context.Context, username string) (GetOwnerByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getOwnerByUsername, username)
	var i GetOwnerByUsernameRow
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const listOwners = `-- name: ListOwners :many
SELECT id, email, username, password_hash, created_at, updated_at FROM owners
ORDER BY id
`

func (q *Queries) ListOwners(ctx context.Context) ([]Owner, error) {
	rows, err := q.db.Query(ctx, listOwners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Owner
	for rows.Next() {
		var i Owner
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
