// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: owner_sessions.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOwnerSession = `-- name: CreateOwnerSession :one
INSERT INTO owner_sessions (owner_id, expires_at) 
VALUES ($1, $2) RETURNING id, owner_id, expires_at, created_at, updated_at
`

type CreateOwnerSessionParams struct {
	OwnerID   int64              `json:"owner_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOwnerSession(ctx context.Context, arg CreateOwnerSessionParams) (OwnerSession, error) {
	row := q.db.QueryRow(ctx, createOwnerSession, arg.OwnerID, arg.ExpiresAt)
	var i OwnerSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredOwnerSessions = `-- name: DeleteExpiredOwnerSessions :many
DELETE FROM owner_sessions
WHERE expires_at < NOW() RETURNING id, owner_id, expires_at, created_at, updated_at
`

func (q *Queries) DeleteExpiredOwnerSessions(ctx context.Context) ([]OwnerSession, error) {
	rows, err := q.db.Query(ctx, deleteExpiredOwnerSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerSession
	for rows.Next() {
		var i OwnerSession
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOwnerSession = `-- name: DeleteOwnerSession :one
DELETE FROM owner_sessions
WHERE id = $1 RETURNING id, owner_id, expires_at, created_at, updated_at
`

func (q *Queries) DeleteOwnerSession(ctx context.Context, id pgtype.UUID) (OwnerSession, error) {
	row := q.db.QueryRow(ctx, deleteOwnerSession, id)
	var i OwnerSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnerSession = `-- name: GetOwnerSession :one
SELECT id, owner_id, expires_at, created_at, updated_at FROM owner_sessions
WHERE id = $1
`

func (q *Queries) GetOwnerSession(ctx context.Context, sessionID pgtype.UUID) (OwnerSession, error) {
	row := q.db.QueryRow(ctx, getOwnerSession, sessionID)
	var i OwnerSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOwnerSession = `-- name: UpdateOwnerSession :one
UPDATE owner_sessions
SET id = gen_random_uuid(),
  expires_at = $1,
  updated_at = $2
WHERE id = $3 RETURNING id, owner_id, expires_at, created_at, updated_at
`

type UpdateOwnerSessionParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	SessionID pgtype.UUID        `json:"session_id"`
}

func (q *Queries) UpdateOwnerSession(ctx context.Context, arg UpdateOwnerSessionParams) (OwnerSession, error) {
	row := q.db.QueryRow(ctx, updateOwnerSession, arg.ExpiresAt, arg.UpdatedAt, arg.SessionID)
	var i OwnerSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
