// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pharmacy_sessions.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPharmacySession = `-- name: CreatePharmacySession :one
INSERT INTO pharmacy_sessions (pharmacy_id, expires_at) 
VALUES ($1, $2) RETURNING id, pharmacy_id, expires_at, created_at, updated_at
`

type CreatePharmacySessionParams struct {
	PharmacyID int64              `json:"pharmacy_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePharmacySession(ctx context.Context, arg CreatePharmacySessionParams) (PharmacySession, error) {
	row := q.db.QueryRow(ctx, createPharmacySession, arg.PharmacyID, arg.ExpiresAt)
	var i PharmacySession
	err := row.Scan(
		&i.ID,
		&i.PharmacyID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredPharmacySessions = `-- name: DeleteExpiredPharmacySessions :many
DELETE FROM pharmacy_sessions
WHERE expires_at < NOW() RETURNING id, pharmacy_id, expires_at, created_at, updated_at
`

func (q *Queries) DeleteExpiredPharmacySessions(ctx context.Context) ([]PharmacySession, error) {
	rows, err := q.db.Query(ctx, deleteExpiredPharmacySessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PharmacySession
	for rows.Next() {
		var i PharmacySession
		if err := rows.Scan(
			&i.ID,
			&i.PharmacyID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePharmacySession = `-- name: DeletePharmacySession :one
DELETE FROM pharmacy_sessions
WHERE id = $1 RETURNING id, pharmacy_id, expires_at, created_at, updated_at
`

func (q *Queries) DeletePharmacySession(ctx context.Context, id pgtype.UUID) (PharmacySession, error) {
	row := q.db.QueryRow(ctx, deletePharmacySession, id)
	var i PharmacySession
	err := row.Scan(
		&i.ID,
		&i.PharmacyID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPharmacySession = `-- name: GetPharmacySession :one
SELECT id, pharmacy_id, expires_at, created_at, updated_at FROM pharmacy_sessions
WHERE id = $1
`

func (q *Queries) GetPharmacySession(ctx context.Context, sessionID pgtype.UUID) (PharmacySession, error) {
	row := q.db.QueryRow(ctx, getPharmacySession, sessionID)
	var i PharmacySession
	err := row.Scan(
		&i.ID,
		&i.PharmacyID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePharmacySession = `-- name: UpdatePharmacySession :one
UPDATE pharmacy_sessions
SET id = gen_random_uuid(),
  expires_at = $1,
  updated_at = $2
WHERE id = $3 RETURNING id, pharmacy_id, expires_at, created_at, updated_at
`

type UpdatePharmacySessionParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	SessionID pgtype.UUID        `json:"session_id"`
}

func (q *Queries) UpdatePharmacySession(ctx context.Context, arg UpdatePharmacySessionParams) (PharmacySession, error) {
	row := q.db.QueryRow(ctx, updatePharmacySession, arg.ExpiresAt, arg.UpdatedAt, arg.SessionID)
	var i PharmacySession
	err := row.Scan(
		&i.ID,
		&i.PharmacyID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
