// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pharmacy_codes.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApotekCode = `-- name: CreateApotekCode :one
INSERT INTO pharmacy_codes (apotek_id, code, expires_at) 
VALUES ($1, $2, $3) RETURNING apotek_id, code, expires_at, created_at, updated_at
`

type CreateApotekCodeParams struct {
	ApotekID  int64              `json:"apotek_id"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateApotekCode(ctx context.Context, arg CreateApotekCodeParams) (PharmacyCode, error) {
	row := q.db.QueryRow(ctx, createApotekCode, arg.ApotekID, arg.Code, arg.ExpiresAt)
	var i PharmacyCode
	err := row.Scan(
		&i.ApotekID,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredApotekCode = `-- name: DeleteExpiredApotekCode :many
DELETE FROM pharmacy_codes
WHERE expires_at < NOW() RETURNING apotek_id, code, expires_at, created_at, updated_at
`

func (q *Queries) DeleteExpiredApotekCode(ctx context.Context) ([]PharmacyCode, error) {
	rows, err := q.db.Query(ctx, deleteExpiredApotekCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PharmacyCode
	for rows.Next() {
		var i PharmacyCode
		if err := rows.Scan(
			&i.ApotekID,
			&i.Code,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePharmacyCode = `-- name: DeletePharmacyCode :one
DELETE FROM pharmacy_codes
WHERE code = $1 RETURNING apotek_id, code, expires_at, created_at, updated_at
`

func (q *Queries) DeletePharmacyCode(ctx context.Context, code string) (PharmacyCode, error) {
	row := q.db.QueryRow(ctx, deletePharmacyCode, code)
	var i PharmacyCode
	err := row.Scan(
		&i.ApotekID,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApotekCode = `-- name: GetApotekCode :one
SELECT apotek_id, code, expires_at, created_at, updated_at FROM pharmacy_codes
WHERE apotek_id = $1
`

func (q *Queries) GetApotekCode(ctx context.Context, apotekID int64) (PharmacyCode, error) {
	row := q.db.QueryRow(ctx, getApotekCode, apotekID)
	var i PharmacyCode
	err := row.Scan(
		&i.ApotekID,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApotekCodeByCode = `-- name: GetApotekCodeByCode :one
SELECT apotek_id, code, expires_at, created_at, updated_at FROM pharmacy_codes
WHERE code = $1
`

func (q *Queries) GetApotekCodeByCode(ctx context.Context, code string) (PharmacyCode, error) {
	row := q.db.QueryRow(ctx, getApotekCodeByCode, code)
	var i PharmacyCode
	err := row.Scan(
		&i.ApotekID,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertApotekCode = `-- name: UpsertApotekCode :one
INSERT INTO pharmacy_codes (apotek_id, code, expires_at) 
VALUES ($1, $2, $3) 
ON CONFLICT (apotek_id) DO UPDATE SET code = excluded.code, expires_at = excluded.expires_at
RETURNING apotek_id, code, expires_at, created_at, updated_at
`

type UpsertApotekCodeParams struct {
	ApotekID  int64              `json:"apotek_id"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertApotekCode(ctx context.Context, arg UpsertApotekCodeParams) (PharmacyCode, error) {
	row := q.db.QueryRow(ctx, upsertApotekCode, arg.ApotekID, arg.Code, arg.ExpiresAt)
	var i PharmacyCode
	err := row.Scan(
		&i.ApotekID,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
