// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"context"
)

type Querier interface {
	CreateOwner(ctx context.Context, arg CreateOwnerParams) (CreateOwnerRow, error)
	ListOwners(ctx context.Context) ([]Owner, error)
}

var _ Querier = (*Queries)(nil)
