// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revoked_sessions.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRevokedSession = `-- name: CreateRevokedSession :one
INSERT INTO revoked_sessions (session_id, expires) 
VALUES ($1, $2) RETURNING id, session_id, expires, created_at, updated_at
`

type CreateRevokedSessionParams struct {
	SessionID string             `json:"session_id"`
	Expires   pgtype.Timestamptz `json:"expires"`
}

func (q *Queries) CreateRevokedSession(ctx context.Context, arg CreateRevokedSessionParams) (RevokedSession, error) {
	row := q.db.QueryRow(ctx, createRevokedSession, arg.SessionID, arg.Expires)
	var i RevokedSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Expires,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
