// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sqids_config.sql

package dbsqlc

import (
	"context"
)

const getAlphabets = `-- name: GetAlphabets :one
SELECT alphabets FROM sqids_config
`

func (q *Queries) GetAlphabets(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getAlphabets)
	var alphabets string
	err := row.Scan(&alphabets)
	return alphabets, err
}
