// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_sessions.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions (user_id, expires_at) 
VALUES ($1, $2) RETURNING id, user_id, expires_at, created_at, updated_at
`

type CreateUserSessionParams struct {
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createUserSession, arg.UserID, arg.ExpiresAt)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredUserSessions = `-- name: DeleteExpiredUserSessions :many
DELETE FROM user_sessions
WHERE expires_at < NOW() RETURNING id, user_id, expires_at, created_at, updated_at
`

func (q *Queries) DeleteExpiredUserSessions(ctx context.Context) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, deleteExpiredUserSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSession
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUserSession = `-- name: DeleteUserSession :one
DELETE FROM user_sessions
WHERE id = $1 RETURNING id, user_id, expires_at, created_at, updated_at
`

func (q *Queries) DeleteUserSession(ctx context.Context, id pgtype.UUID) (UserSession, error) {
	row := q.db.QueryRow(ctx, deleteUserSession, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSession = `-- name: GetUserSession :one
SELECT id, user_id, expires_at, created_at, updated_at FROM user_sessions
WHERE id = $1
`

func (q *Queries) GetUserSession(ctx context.Context, sessionID pgtype.UUID) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSession, sessionID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserSession = `-- name: UpdateUserSession :one
UPDATE user_sessions
SET id = gen_random_uuid(),
  expires_at = $1,
  updated_at = $2
WHERE id = $3 RETURNING id, user_id, expires_at, created_at, updated_at
`

type UpdateUserSessionParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	SessionID pgtype.UUID        `json:"session_id"`
}

func (q *Queries) UpdateUserSession(ctx context.Context, arg UpdateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, updateUserSession, arg.ExpiresAt, arg.UpdatedAt, arg.SessionID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
